#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputs = [
  {
    schemaPath: "schemas/clerk-catalog.v1.schema.json",
    outputPath: "src/generated/clerk-catalog.v1.ts",
    identifier: "clerk-catalog.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type ClerkCatalogFreshnessV1 = "current" | "unknown";\nexport type ClerkCatalogStatusV1 = "active" | "archived";\nexport type ClerkCatalogExecutionV1 = "agent" | "human";\n\nexport interface ClerkCatalogEntryV1 {\n  name: string;\n  status: ClerkCatalogStatusV1;\n  builtIn: boolean;\n  execution: ClerkCatalogExecutionV1;\n  approvedCommit: string;\n  description: string;\n}\n\nexport interface ClerkCatalogOmissionV1 {\n  name: string;\n  reason: string;\n}\n\nexport interface ClerkCatalogV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: ClerkCatalogFreshnessV1;\n  provenance: { registrySchema: "clerk-registry.v1" };\n  clerks: ClerkCatalogEntryV1[];\n  omitted: ClerkCatalogOmissionV1[];\n  errors: string[];\n}\n`,
  },
  {
    schemaPath: "schemas/conversation-sessions.v1.schema.json",
    outputPath: "src/generated/conversation-sessions.v1.ts",
    identifier: "clerkmesh.conversation-sessions.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport interface ConversationSessionV1 {\n  id: string;\n  name: string | null;\n  createdAt: string;\n  modifiedAt: string;\n  messageCount: number;\n}\n\nexport interface ConversationSessionsV1 {\n  schema: "${id}";\n  observedAt: string;\n  sessions: ConversationSessionV1[];\n  errors: string[];\n}\n`,
  },
  {
    schemaPath: "schemas/clerkmesh.execution-context.v1.schema.json",
    outputPath: "src/generated/clerkmesh.execution-context.v1.ts",
    identifier: "clerkmesh.execution-context.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type ClerkExecutionV1 = "agent" | "human";\n\nexport interface ExecutionContextAllowlistEntryV1 {\n  path: string;\n  name: string;\n  description: string;\n  blobOid: string;\n}\n\nexport interface ClerkmeshExecutionContextV1 {\n  schema: "${id}";\n  taskId: string;\n  clerk: { name: string; execution: ClerkExecutionV1; commit: string };\n  identity: { role: string; workingStyle: string; instructions: string };\n  selection: { reason: string; boundaries: string };\n  allowlist: ExecutionContextAllowlistEntryV1[];\n}\n`,
  },
  {
    schemaPath: "schemas/conversation-events.v1.schema.json",
    outputPath: "src/generated/conversation-events.v1.ts",
    identifier: "clerkmesh.conversation-events.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type ConversationEventKindV1 = "visible-message" | "stream-fragment" | "notification" | "error" | "primary-status" | "extension-ui" | "diagnostic";\n\nexport interface ConversationEventV1 {\n  sequence: number;\n  kind: ConversationEventKindV1;\n  payload: Record<string, unknown>;\n}\n\nexport interface ConversationEventsV1 {\n  schema: "${id}";\n  observedAt: string;\n  cursor: number;\n  events: ConversationEventV1[];\n}\n`,
  },
];

for (const item of outputs) {
  const schemaPath = resolve(root, item.schemaPath);
  const outputPath = resolve(root, item.outputPath);
  const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
  if (schema.properties?.schema?.const !== item.identifier) throw new Error(`unexpected schema identifier: ${schemaPath}`);
  const output = item.render(item.identifier);
  if (process.argv.includes("--check")) {
    if (readFileSync(outputPath, "utf8") !== output) throw new Error(`generated type is stale: ${outputPath}`);
  } else {
    writeFileSync(outputPath, output);
  }
}
