#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputs = [
  {
    schemaPath: "schemas/learning-proposal.v1.schema.json",
    outputPath: "src/generated/learning-proposal.v1.ts",
    identifier: "learning-proposal.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport interface LearningReviewTargetV1 {\n  name: string;\n  state: string;\n  source: { id: string; contentSha256: string; preview: string };\n  changedPaths: string[];\n  fullDiff: string;\n  identity: { baseCommit: string; candidateTree: string };\n  warnings: string[];\n  validation: { status: string; markdownOnly: boolean };\n  preparedAt: string;\n  reviewedAt: string | null;\n  decision: null | { outcome: "approved" | "rejected"; decidedAt: string; resultCommit: string | null };\n}\n\nexport interface LearningProposalV1 {\n  schema: "${id}";\n  id: string;\n  state: string;\n  createdAt: string;\n  resolvedAt: string | null;\n  targets: LearningReviewTargetV1[];\n}\n`,
  },
  {
    schemaPath: "schemas/learning-list.v1.schema.json",
    outputPath: "src/generated/learning-list.v1.ts",
    identifier: "learning-list.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nimport type { LearningProposalV1 } from "./learning-proposal.v1.js";\n\nexport interface LearningListV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: "current" | "unknown";\n  provenance: { authority: "clerkmesh-learning-proposals" };\n  proposals: LearningProposalV1[];\n  omitted: Array<{ proposalId?: string; reason: string }>;\n  errors: Array<{ reason: string }>;\n}\n`,
  },
  {
    schemaPath: "schemas/fm-task-activity.v1.schema.json",
    outputPath: "src/generated/fm-task-activity.v1.ts",
    identifier: "fm-task-activity.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type FmTaskActivityFreshnessV1 = "current" | "stale" | "unknown";\nexport type FmTaskActivityEventTypeV1 = "task-created" | "dependency-changed" | "dispatch-started" | "worker-status-observed" | "validation-recorded" | "decision-requested" | "decision-recorded" | "delivery-reviewed" | "landed" | "teardown-recorded" | "failed";\n\nexport interface FmTaskActivityEventV1 {\n  cursor: number;\n  type: FmTaskActivityEventTypeV1;\n  observedAt: string;\n  occurredAt: string | null;\n  summary: string;\n}\n\nexport interface FmTaskActivityV1 {\n  schema: "${id}";\n  taskId: string;\n  observedAt: string;\n  freshness: FmTaskActivityFreshnessV1;\n  provenance: { authority: "firstmate"; source: "structured-task-activity" };\n  cursor: number;\n  events: FmTaskActivityEventV1[];\n  omitted: Array<{ reason: string }>;\n  errors: Array<{ reason: string }>;\n}\n`,
  },
  {
    schemaPath: "schemas/fm-herdr-agents.v1.schema.json",
    outputPath: "src/generated/fm-herdr-agents.v1.ts",
    identifier: "fm-herdr-agents.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type FmHerdrFreshnessV1 = "current" | "stale" | "unknown";\nexport type FmHerdrPresenceV1 = "yes" | "no" | "unknown";\nexport type FmHerdrAgentStatusV1 = "working" | "idle" | "done" | "blocked" | "unknown";\n\nexport interface FmHerdrAgentRecordV1 {\n  taskId: string;\n  backend: "herdr";\n  agent: { present: FmHerdrPresenceV1; status: FmHerdrAgentStatusV1; observedAt: string | null; source: "herdr.agent.get" | "unavailable"; reason?: string };\n  endpoint: { exists: FmHerdrPresenceV1 };\n}\n\nexport interface FmHerdrAgentsV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: FmHerdrFreshnessV1;\n  provenance: { authority: "firstmate"; runtime: "herdr" };\n  agents: FmHerdrAgentRecordV1[];\n  omitted: Array<{ taskId?: string; reason: string }>;\n  errors: Array<{ taskId?: string; reason: string }>;\n}\n`,
  },
  {
    schemaPath: "schemas/fm-project-catalog.v1.schema.json",
    outputPath: "src/generated/fm-project-catalog.v1.ts",
    identifier: "fm-project-catalog.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type FmProjectCatalogFreshnessV1 = "current" | "stale" | "unknown";\nexport type FmProjectRegistrationV1 = "registered" | "discovered" | "missing";\nexport type FmProjectDeliveryModeV1 = "local-only" | "direct-PR" | "no-mistakes" | "unknown";\n\nexport interface FmProjectCatalogEntryV1 {\n  id: string;\n  name: string;\n  registration: FmProjectRegistrationV1;\n  present: boolean;\n  git: boolean;\n  remote: string | null;\n  delivery: { mode: FmProjectDeliveryModeV1; yolo: boolean };\n}\n\nexport interface FmProjectCatalogV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: FmProjectCatalogFreshnessV1;\n  provenance: { authority: "firstmate" };\n  projects: FmProjectCatalogEntryV1[];\n  omitted: Array<{ projectId?: string; reason: string }>;\n  errors: Array<{ projectId?: string; reason: string }>;\n}\n`,
  },
  {
    schemaPath: "schemas/clerkmesh-task-detail.v1.schema.json",
    outputPath: "src/generated/clerkmesh-task-detail.v1.ts",
    identifier: "clerkmesh-task-detail.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nimport type { FmTaskGraphTaskV1, FmTaskGraphFreshnessV1 } from "./fm-task-graph.v1.js";\n\nexport interface ClerkmeshTaskDetailV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: FmTaskGraphFreshnessV1;\n  provenance: { taskAuthority: "firstmate"; executionClerkAuthority: "current-brief-execution-context" };\n  task: FmTaskGraphTaskV1;\n  execution_clerk: null | { name: string; execution: "agent" | "human"; commit: string; contextSha256: string; relationship: "current-or-most-recent-execution" };\n  omitted: Array<{ reason: string }>;\n  errors: Array<{ reason: string }>;\n}\n`,
  },
  {
    schemaPath: "schemas/fm-task-graph.v1.schema.json",
    outputPath: "src/generated/fm-task-graph.v1.ts",
    identifier: "fm-task-graph.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type FmTaskGraphFreshnessV1 = "current" | "stale" | "unknown";\nexport type FmTaskPhaseV1 = "planned" | "ready" | "dispatched" | "executing" | "validating" | "awaiting_decision" | "awaiting_dependency" | "completed" | "failed" | "cancelled" | "unknown";\n\nexport interface FmTaskGraphTaskV1 {\n  id: string;\n  title: string;\n  projectId: string;\n  kind: string;\n  backlogState: "queued" | "in_flight" | "done" | "unknown";\n  phase: FmTaskPhaseV1;\n  wait: null | { kind: "dependency" | "captain_decision" | "external" | "runtime_blocked" | "paused" | "unknown"; reason: string; blockerIds: string[]; since: string | null; actionableBy: "captain" | "primary" | "worker" | "external" | "unknown" };\n  runtime: { state: string; source: string; observedAt: string | null };\n  results: Array<{ kind: "pr" | "report" | "commit" | "external"; href: string; label: string; status: string }>;\n}\n\nexport interface FmTaskGraphV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: FmTaskGraphFreshnessV1;\n  provenance: { authority: "firstmate" };\n  tasks: FmTaskGraphTaskV1[];\n  edges: Array<{ type: "blocks"; from: string; to: string; resolved: boolean }>;\n  omitted: Array<{ taskId?: string; reason: string }>;\n  errors: Array<{ taskId?: string; reason: string }>;\n}\n`,
  },
  {
    schemaPath: "schemas/clerk-catalog.v1.schema.json",
    outputPath: "src/generated/clerk-catalog.v1.ts",
    identifier: "clerk-catalog.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type ClerkCatalogFreshnessV1 = "current" | "unknown";\nexport type ClerkCatalogStatusV1 = "active" | "archived";\nexport type ClerkCatalogExecutionV1 = "agent" | "human";\n\nexport interface ClerkCatalogEntryV1 {\n  name: string;\n  status: ClerkCatalogStatusV1;\n  builtIn: boolean;\n  execution: ClerkCatalogExecutionV1;\n  approvedCommit: string;\n  description: string;\n}\n\nexport interface ClerkCatalogOmissionV1 {\n  name: string;\n  reason: string;\n}\n\nexport interface ClerkCatalogV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: ClerkCatalogFreshnessV1;\n  provenance: { registrySchema: "clerk-registry.v1" };\n  clerks: ClerkCatalogEntryV1[];\n  omitted: ClerkCatalogOmissionV1[];\n  errors: string[];\n}\n`,
  },
  {
    schemaPath: "schemas/conversation-sessions.v1.schema.json",
    outputPath: "src/generated/conversation-sessions.v1.ts",
    identifier: "clerkmesh.conversation-sessions.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport interface ConversationSessionV1 {\n  id: string;\n  name: string | null;\n  createdAt: string;\n  modifiedAt: string;\n  messageCount: number;\n}\n\nexport interface ConversationSessionsV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: "current" | "unknown";\n  provenance: { authority: "pi-session-jsonl" };\n  sessions: ConversationSessionV1[];\n  omitted: Array<{ reason: string }>;\n  errors: string[];\n}\n`,
  },
  {
    schemaPath: "schemas/clerkmesh.execution-context.v1.schema.json",
    outputPath: "src/generated/clerkmesh.execution-context.v1.ts",
    identifier: "clerkmesh.execution-context.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type ClerkExecutionV1 = "agent" | "human";\n\nexport interface ExecutionContextAllowlistEntryV1 {\n  path: string;\n  name: string;\n  description: string;\n  blobOid: string;\n}\n\nexport interface ClerkmeshExecutionContextV1 {\n  schema: "${id}";\n  taskId: string;\n  clerk: { name: string; execution: ClerkExecutionV1; commit: string };\n  identity: { role: string; workingStyle: string; instructions: string };\n  selection: { reason: string; boundaries: string };\n  allowlist: ExecutionContextAllowlistEntryV1[];\n}\n`,
  },
  {
    schemaPath: "schemas/conversation-events.v1.schema.json",
    outputPath: "src/generated/conversation-events.v1.ts",
    identifier: "clerkmesh.conversation-events.v1",
    render: (id) => `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport type ConversationEventKindV1 = "visible-message" | "stream-fragment" | "notification" | "error" | "primary-status" | "extension-ui" | "diagnostic";\n\nexport interface ConversationEventV1 {\n  sequence: number;\n  kind: ConversationEventKindV1;\n  payload: Record<string, unknown>;\n}\n\nexport interface ConversationEventsV1 {\n  schema: "${id}";\n  observedAt: string;\n  freshness: "current" | "unknown";\n  provenance: { authority: "pi-session-jsonl"; projection: "process-local-pi-rpc-events" };\n  cursor: number;\n  events: ConversationEventV1[];\n  omitted: Array<{ reason: string }>;\n  errors: string[];\n}\n`,
  },
];

for (const item of outputs) {
  const schemaPath = resolve(root, item.schemaPath);
  const outputPath = resolve(root, item.outputPath);
  const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
  if (schema.properties?.schema?.const !== item.identifier) throw new Error(`unexpected schema identifier: ${schemaPath}`);
  const output = item.render(item.identifier);
  if (process.argv.includes("--check")) {
    if (readFileSync(outputPath, "utf8") !== output) throw new Error(`generated type is stale: ${outputPath}`);
  } else {
    writeFileSync(outputPath, output);
  }
}
