#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = resolve(root, "schemas/conversation-sessions.v1.schema.json");
const outputPath = resolve(root, "src/generated/conversation-sessions.v1.ts");
const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
if (schema.properties?.schema?.const !== "clerkmesh.conversation-sessions.v1") {
  throw new Error("unexpected conversation session schema identifier");
}
const output = `// Generated by packages/shared/scripts/generate-types.mjs. Do not edit.\n\nexport interface ConversationSessionV1 {\n  id: string;\n  name: string | null;\n  createdAt: string;\n  modifiedAt: string;\n  messageCount: number;\n}\n\nexport interface ConversationSessionsV1 {\n  schema: \"${schema.properties.schema.const}\";\n  observedAt: string;\n  sessions: ConversationSessionV1[];\n  errors: string[];\n}\n`;

if (process.argv.includes("--check")) {
  if (readFileSync(outputPath, "utf8") !== output) {
    throw new Error(`generated type is stale: ${outputPath}`);
  }
} else {
  writeFileSync(outputPath, output);
}
